### ISSUE TITLE
dallar ile nasl çalışılıyor

### ISSUE THREAD

**Issue by alidurmus** [korayzorluoglu/miisAlisveris#1]
Languages dalını nasıl geri yükleyeceğim ? 

Bir isimlendirme planımız var mı ?

**Comment by korayzorluoglu** [comment]
```
git clone https://github.com/korayzorluoglu/miisAlisveris.git
touch database/database.sql
composer install
php artisan key:generate
php artisan migrate
php artisan db:seed
php artisan currency:update
```
kurulumdan sonra komut satirina
`git checkout languages`
yazarak languages dalina gecebilirsiniz,

daha sonra dil ile degisikleri yaparsiniz, tüm degisiklikelr bittikten sonra sirasiyla
```
git add .
git commit -m "Dil ile iligli sunlari snlaru yaptim, sunlari cikardim, vb. aciklamalar vs."
git push origin languages
```
yaparak güncellemeleriniz languages dalina gelmis olur. Daha sonra diyelim ki dil islemleri tamamlandi ve hersey bittiyse, commit'ini Pull Request ile bana bildirirsin, bende onu master yani suanki asil projede eklemis olurum.

burada genel manada bir anlatim mevcut genel teknik terimler icin;
http://rogerdudler.github.io/git-guide/index.tr.html

**Comment by alidurmus** [comment]
Tamam ben şuan yönetim paneli olan dil eklentisi üzerinde çalışıyorum. işlemler bitince sana bildiririm

**Comment by alidurmus** [comment]
Birçok alanda değişiklik yapmam gerekti. Bunları anlatmam biraz zor olacak. İzin vermen gerekiyor  galiba  git push origin languages komutundan sonra izin istiyor

**Comment by korayzorluoglu** [comment]
izinden kastiniz nedir tam anliyamadim?

**Comment by alidurmus** [comment]
git push origin languages

remote: Permission to korayzorluoglu/miisAlisveris.git denied to alidurmus.
fatal: unable to access 'https://github.com/korayzorluoglu/miisAlisveris.git/': The requested URL returned error: 403


Bu hatayı alıyorum

**Comment by korayzorluoglu** [comment]
tekrar denermisin, eger yine olmaz ise asagidaki linkten rsa sifresini tekrar üretip denermisin? https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

**Comment by alidurmus** [comment]
Tamam yüklüyor. Eksikleri var ama veri tabanında isimlere ekleme yapmam gerekti

**Comment by korayzorluoglu** [comment]
tamamdir bir sonraki adim olan pull request icin bu blog'a bakabilirsiniz.
https://kodcu.com/2015/03/pull-request-nedir-nasil-yapilir/

**Comment by alidurmus** [comment]
Tamam . Biraz acemiyim bu konularda yorumları falan tam yazamadım galiba.

**Comment by korayzorluoglu** [comment]
hic önemi yok, bende sizin gibi ögrenerek ilerliyorum.
